// <auto-generated />
namespace Intranet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartelleClinichehref : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartelleClinichehref));
        
        string IMigrationMetadata.Id
        {
            get { return "201701251404556_CartelleClinichehref"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
